# Generated by Django 5.2.7 on 2025-10-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome único para identificar o parâmetro.', max_length=100, unique=True, verbose_name='Nome')),
                ('valor', models.CharField(blank=True, help_text='Valor do parâmetro. Pode ser texto, número, etc.', max_length=255, verbose_name='Valor')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do parâmetro.', null=True, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
            ],
            options={
                'verbose_name': 'Parâmetro',
                'verbose_name_plural': 'Parâmetros',
            },
        ),
    ]
