# Generated by Django 5.2.7 on 2025-10-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametro',
            name='descricao',
            field=models.CharField(blank=True, help_text='Descrição detalhada do parâmetro.', max_length=128, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='valor',
            field=models.CharField(blank=True, help_text='Valor do parâmetro. Pode ser texto, número, etc.', max_length=128, verbose_name='Valor'),
        ),
    ]
