# Generated by Django 5.2.7 on 2025-10-21 13:08

import cadastros.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, validators=[cadastros.validators.validate_cnpj]),
        ),
        migrations.AlterField(
            model_name='filial',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, validators=[cadastros.validators.validate_cnpj]),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[cadastros.validators.validate_cpf]),
        ),
    ]
